version: '3.3'
services:
  ssidd01111:
    image: san:san
    volumes:
      - /home/ubuntu/docker/mysql.sh:/mysql/mysql.sh
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: ["sleep 10 && /mysql/mysql.sh"]
    ports:
      - 3306:3306
        #volumes:
        # - mysql_db_data_container:/var/lib/mysql

database:
    image: mysql:5.7
    ports:
        - "33061:3306"
    command: --init-file /data/application/init.sql
    volumes:
        - ./init.sql:/data/application/init.sql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: homestead
        MYSQL_USER: root
        MYSQL_PASSWORD: secret
